[package]
name = "rust-tetris-sdl"
version = "0.1.0"
authors = ["Andrew Jones <andrew.jones@rea-group.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.34.3"
libc = "0.2.76"
